name = "brbtraining"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[ kv_namespaces ]]
binding = "BRB_KV"
id = "ce44f82dceff46a6bd16563a2f3a3b1c"
preview_id = "ce44f82dceff46a6bd16563a2f3a3b1c"
